apiVersion: v1
kind: Secret
metadata:
  name: excalibur-core-secrets
  namespace: excalibur-gym
type: Opaque
stringData:
  CORE_DATABASE_USERNAME: replace-me
  CORE_DATABASE_PASSWORD: replace-me
  REPORTING_INTERNAL_API_KEY: replace-with-at-least-32-random-characters
  SAUNA_INTERNAL_API_KEY: replace-with-at-least-32-random-characters
  SOLARIUM_INTERNAL_API_KEY: replace-with-at-least-32-random-characters
---
apiVersion: v1
kind: Secret
metadata:
  name: excalibur-reporting-secrets
  namespace: excalibur-gym
type: Opaque
stringData:
  REPORTING_DATABASE_USERNAME: replace-me
  REPORTING_DATABASE_PASSWORD: replace-me
  REPORTING_INTERNAL_API_KEY: replace-with-the-same-32-character-value

---
apiVersion: v1
kind: Secret
metadata:
  name: excalibur-sauna-secrets
  namespace: excalibur-gym
type: Opaque
stringData:
  SAUNA_DATABASE_USERNAME: replace-me
  SAUNA_DATABASE_PASSWORD: replace-me
  SAUNA_INTERNAL_API_KEY: replace-with-the-same-32-character-value

---
apiVersion: v1
kind: Secret
metadata:
  name: excalibur-solarium-secrets
  namespace: excalibur-gym
type: Opaque
stringData:
  SOLARIUM_DATABASE_USERNAME: replace-me
  SOLARIUM_DATABASE_PASSWORD: replace-me
  SOLARIUM_INTERNAL_API_KEY: replace-with-the-same-32-character-value
