apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - core-service.yaml
  - reporting-service.yaml
  - sauna-service.yaml
  - solarium-service.yaml
  - frontend.yaml
  - ingress.yaml
